/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package moneycalculator;


/**
 *
 * @author Pablo
 */
public class MoneyCalculatorFrame extends javax.swing.JFrame {

    /**
     * Creates new form MoneyCalculatorFrame
     */
    public MoneyCalculatorFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ratioPanel = new javax.swing.JPanel();
        leftRatioLabel = new javax.swing.JLabel();
        ratioField = new javax.swing.JTextField();
        rightRatioLabel = new javax.swing.JLabel();
        conversionPanel = new javax.swing.JPanel();
        conversionTitleLabel = new javax.swing.JLabel();
        euroField = new javax.swing.JTextField();
        usdField = new javax.swing.JTextField();
        euroLabel = new javax.swing.JLabel();
        usdLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conversor de monedas (EUR, USD)");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        leftRatioLabel.setText("1 € equivale a ");

        ratioField.setText("1.17");
        ratioField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ratioFieldActionPerformed(evt);
            }
        });
        ratioField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ratioFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ratioFieldKeyTyped(evt);
            }
        });

        rightRatioLabel.setText("$ US");

        javax.swing.GroupLayout ratioPanelLayout = new javax.swing.GroupLayout(ratioPanel);
        ratioPanel.setLayout(ratioPanelLayout);
        ratioPanelLayout.setHorizontalGroup(
            ratioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ratioPanelLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(leftRatioLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ratioField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rightRatioLabel)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        ratioPanelLayout.setVerticalGroup(
            ratioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ratioPanelLayout.createSequentialGroup()
                .addGroup(ratioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(leftRatioLabel)
                    .addComponent(ratioField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rightRatioLabel))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        conversionPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        conversionTitleLabel.setText("Inserte el valor a convertir");

        euroField.setText("0.0");
        euroField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                euroFieldActionPerformed(evt);
            }
        });
        euroField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                euroFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                euroFieldKeyTyped(evt);
            }
        });

        usdField.setText("0.0");
        usdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usdFieldActionPerformed(evt);
            }
        });
        usdField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                usdFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                usdFieldKeyTyped(evt);
            }
        });

        euroLabel.setText("EUR");

        usdLabel.setText("USD");

        javax.swing.GroupLayout conversionPanelLayout = new javax.swing.GroupLayout(conversionPanel);
        conversionPanel.setLayout(conversionPanelLayout);
        conversionPanelLayout.setHorizontalGroup(
            conversionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(conversionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(conversionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(conversionTitleLabel)
                    .addGroup(conversionPanelLayout.createSequentialGroup()
                        .addGroup(conversionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(usdField, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                            .addComponent(euroField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(conversionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(euroLabel)
                            .addComponent(usdLabel, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        conversionPanelLayout.setVerticalGroup(
            conversionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(conversionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(conversionTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(conversionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(euroField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(euroLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(conversionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usdLabel))
                .addContainerGap())
        );

        jLabel1.setText("Christian García Viguera");

        jLabel2.setText("Pablo Ortigosa Quevedo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ratioPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(conversionPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ratioPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(conversionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ratioFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ratioFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ratioFieldActionPerformed

    private void usdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usdFieldActionPerformed

    private void euroFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_euroFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_euroFieldActionPerformed

    private void euroFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_euroFieldKeyReleased
        float ratio;
        float eur;
        try {
            ratio = Float.parseFloat(ratioField.getText());
            eur = Float.parseFloat(euroField.getText());
        } catch (java.lang.NumberFormatException e) {
            return;
        }
        ratio = ((float) java.lang.Math.round(ratio * 100))/100; 
        eur = ((float) java.lang.Math.round(eur * 100))/100; 
        usdField.setText(String.valueOf(((float) java.lang.Math.round(ratio*eur*100))/100));
    }//GEN-LAST:event_euroFieldKeyReleased

    private void euroFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_euroFieldKeyTyped
        keyCatcher(euroField, evt);
    }//GEN-LAST:event_euroFieldKeyTyped

    private void usdFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usdFieldKeyTyped
        keyCatcher(usdField, evt);

    }//GEN-LAST:event_usdFieldKeyTyped

    private void ratioFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ratioFieldKeyTyped
        keyCatcher(ratioField, evt);
    }//GEN-LAST:event_ratioFieldKeyTyped

    private void usdFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usdFieldKeyReleased
        float ratio;
        float dolar;
        try {
            ratio = 1/Float.parseFloat(ratioField.getText());
            dolar = Float.parseFloat(usdField.getText());
        } catch (java.lang.NumberFormatException e) {
            return;
        }
        ratio = ((float) java.lang.Math.round(ratio * 100))/100; 
        dolar = ((float) java.lang.Math.round(dolar * 100))/100; 
        euroField.setText(String.valueOf(((float) java.lang.Math.round(ratio*dolar*100))/100));
    }//GEN-LAST:event_usdFieldKeyReleased

    private void ratioFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ratioFieldKeyReleased
        float ratio;
        float eur;
        try {
            ratio = Float.parseFloat(ratioField.getText());
            eur = Float.parseFloat(euroField.getText());
        } catch (java.lang.NumberFormatException e) {
            return;
        }
        ratio = ((float) java.lang.Math.round(ratio * 100))/100;
        eur = ((float) java.lang.Math.round(eur * 100))/100; 
        usdField.setText(String.valueOf(((float) java.lang.Math.round(ratio*eur*100))/100));
    }//GEN-LAST:event_ratioFieldKeyReleased

    public void keyCatcher(javax.swing.JTextField field,java.awt.event.KeyEvent evt){
        char key = evt.getKeyChar();
        if(!Character.isDigit(key) && key != '.'){
            evt.consume();
        }
        if (key == '.'){
            String thisText = field.getText();
            for (int i = 0; i < thisText.length(); i++) {
                if (thisText.charAt(i) == '.'){
                    evt.consume();
                    break;
                }
            }
        }        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MoneyCalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MoneyCalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MoneyCalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MoneyCalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MoneyCalculatorFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel conversionPanel;
    private javax.swing.JLabel conversionTitleLabel;
    private javax.swing.JTextField euroField;
    private javax.swing.JLabel euroLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel leftRatioLabel;
    private javax.swing.JTextField ratioField;
    private javax.swing.JPanel ratioPanel;
    private javax.swing.JLabel rightRatioLabel;
    private javax.swing.JTextField usdField;
    private javax.swing.JLabel usdLabel;
    // End of variables declaration//GEN-END:variables
}
